// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sweetheart0330/gopher_mart/internal/models"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// DownloadOrder mocks base method.
func (m *MockController) DownloadOrder(ctx context.Context, userID string, order models.Order) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadOrder", ctx, userID, order)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadOrder indicates an expected call of DownloadOrder.
func (mr *MockControllerMockRecorder) DownloadOrder(ctx, userID, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadOrder", reflect.TypeOf((*MockController)(nil).DownloadOrder), ctx, userID, order)
}

// GetBalance mocks base method.
func (m *MockController) GetBalance(ctx context.Context, userID string) (models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockControllerMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockController)(nil).GetBalance), ctx, userID)
}

// GetOrders mocks base method.
func (m *MockController) GetOrders(ctx context.Context, userID string) ([]models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockControllerMockRecorder) GetOrders(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockController)(nil).GetOrders), ctx, userID)
}

// GetPasswordHash mocks base method.
func (m *MockController) GetPasswordHash(ctx context.Context, login string) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPasswordHash", ctx, login)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPasswordHash indicates an expected call of GetPasswordHash.
func (mr *MockControllerMockRecorder) GetPasswordHash(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPasswordHash", reflect.TypeOf((*MockController)(nil).GetPasswordHash), ctx, login)
}

// GetWithdrawals mocks base method.
func (m *MockController) GetWithdrawals(ctx context.Context, userID string) ([]models.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]models.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockControllerMockRecorder) GetWithdrawals(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockController)(nil).GetWithdrawals), ctx, userID)
}

// OrdersPooler mocks base method.
func (m *MockController) OrdersPooler(ctx context.Context, poolInterval time.Duration, batchSize int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OrdersPooler", ctx, poolInterval, batchSize)
}

// OrdersPooler indicates an expected call of OrdersPooler.
func (mr *MockControllerMockRecorder) OrdersPooler(ctx, poolInterval, batchSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersPooler", reflect.TypeOf((*MockController)(nil).OrdersPooler), ctx, poolInterval, batchSize)
}

// RegisterUser mocks base method.
func (m *MockController) RegisterUser(ctx context.Context, user models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockControllerMockRecorder) RegisterUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockController)(nil).RegisterUser), ctx, user)
}

// WithDrawn mocks base method.
func (m *MockController) WithDrawn(ctx context.Context, userId string, withdraw models.Withdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithDrawn", ctx, userId, withdraw)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithDrawn indicates an expected call of WithDrawn.
func (mr *MockControllerMockRecorder) WithDrawn(ctx, userId, withdraw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithDrawn", reflect.TypeOf((*MockController)(nil).WithDrawn), ctx, userId, withdraw)
}
